### ISSUE TITLE
Add progress icon while loading markets in the homepage

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#600]
Hey guys, when you access the homepage of the DEX you see the below message for 1-2 seconds saying that "there are no markets found", not urgent but would be good if we can maybe display a loading icon opposed to this message.

![image](https://user-images.githubusercontent.com/83584143/158020503-9016f739-1191-4183-8bc8-0b4ee9bf218d.png)

Similarly like we do for the market page to load the orderbook and other components.

![image](https://user-images.githubusercontent.com/83584143/158020646-7b7b3ce8-3832-4732-bc76-e57e45dfaa9f.png)

**Comment by ThomasRalee** [comment]
Resolved in commit [00553e65949aaa969270f1f7999c06fa1a6e48f9](https://github.com/InjectiveLabs/injective-dex/commit/00553e65949aaa969270f1f7999c06fa1a6e48f9)

**Comment by albertchon** [comment]
Same for 
<img width="619" alt="image" src="https://user-images.githubusercontent.com/20461629/158289196-cef242e1-6b8b-446f-a49d-428ebd6c5add.png">

**Comment by ThomasRalee** [comment]
Resolved in commit [fbba940a89b5d6ecd245edc015185c64d889ffc1](https://github.com/InjectiveLabs/injective-dex/commit/fbba940a89b5d6ecd245edc015185c64d889ffc1)

**Comment by achilleas-kal** [comment]
Hey @ThomasRalee this is still happening.

https://www.loom.com/share/8a38dcedc9a643c2bfce8c591124aac1

**Comment by ThomasRalee** [comment]
@achilleas-kal  Resolved in https://github.com/InjectiveLabs/injective-dex/commit/de083082f16cafc1564fd4e58b04fc1f49c9651f
https://www.loom.com/share/0a861e71c0c6432f9f6000b030fc0311
